### ISSUE TITLE
"Already Have a token?" link has incorrect href

### ISSUE THREAD

**Issue by christianbundy** [cryptostorm/website_main#2]
Clicking "Already Have a token? Then you're ready to connect" takes me to [`http://cs.vpndark.net/#section6`](http://cs.vpndark.net/#section6), whereas I'd expect that it takes me to [`#section6`](https://cryptostorm.is/tokens#section6).

**Comment by df-cryptostorm** [comment]
Right you are, fixing it now...
(cs.vpndark.net was the staging server we were using to test out the new website when it was still in a development phase, so no evil hijack happening :-P)
